# Generated by Django 5.2.7 on 2025-10-26 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('metal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gold_purity', models.CharField(blank=True, max_length=10, null=True)),
                ('gold_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('diamond_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('diamond_clarity', models.CharField(blank=True, max_length=20, null=True)),
                ('diamond_color', models.CharField(blank=True, max_length=20, null=True)),
                ('badge', models.CharField(choices=[('NONE', 'None'), ('NEW', 'New Arrival'), ('TRENDING', 'Trending'), ('BEST', 'Best Seller')], default='NONE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='jewellery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(choices=[('NEW', 'New Arrival'), ('SALE', 'On Sale'), ('BEST', 'Best Seller'), ('TRENDING', 'Trending'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('stone_type', models.CharField(choices=[('DIAMOND', 'Diamond'), ('RUBY', 'Ruby'), ('EMERALD', 'Emerald'), ('SAPPHIRE', 'Sapphire'), ('PEARL', 'Pearl'), ('AMETHYST', 'Amethyst'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('color', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('ROSE_GOLD', 'Rose Gold'), ('PLATINUM', 'Platinum'), ('MULTI', 'Multi-color')], default='GOLD', max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
                ('metal_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('PLATINUM', 'Platinum')], default='GOLD', max_length=20)),
                ('gold_purity', models.CharField(choices=[('18K', '18K'), ('22K', '22K'), ('24K', '24K')], default='22K', max_length=10)),
                ('gold_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diamond_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diamond_clarity', models.CharField(blank=True, max_length=50, null=True)),
                ('diamond_color', models.CharField(blank=True, max_length=50, null=True)),
                ('gold_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stone_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('making_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewellery_items', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Jewellery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JewelleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jewellery/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.jewellery')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
