# Generated by Django 5.2.7 on 2025-10-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_alter_wishlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellery',
            name='category',
        ),
        migrations.AddField(
            model_name='jewellery',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewellery_items', to='shop.subcategory'),
        ),
    ]
