# Generated by Django 5.2.7 on 2025-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_jewellery_category_jewellery_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='platinum_purity',
            field=models.CharField(blank=True, choices=[('950', '950 Platinum'), ('900', '900 Platinum'), ('OTHER', 'Other')], default='950', help_text='Platinum purity (only relevant when metal_type is Platinum)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='platinum_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='platinum_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='silver_purity',
            field=models.CharField(blank=True, choices=[('STERLING', 'Sterling (925)'), ('999', '999 Fine Silver'), ('OTHER', 'Other')], default='STERLING', help_text='Silver purity (only relevant when metal_type is Silver)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='silver_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='silver_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='diamond_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='gold_purity',
            field=models.CharField(blank=True, choices=[('18K', '18K'), ('22K', '22K'), ('24K', '24K'), ('OTHER', 'Other')], default='22K', help_text='Gold purity (only relevant when metal_type is Gold)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='gold_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='gold_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='making_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='stone_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
