# Generated by Django 4.2.7 on 2026-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_wishlist_product_alter_wishlist_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metal_type",
                    models.CharField(
                        choices=[("GOLD", "Gold"), ("SILVER", "Silver")], max_length=20
                    ),
                ),
                (
                    "price_per_gram",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "change_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_up", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Metal Prices",
                "ordering": ["metal_type"],
            },
        ),
    ]
