# Generated by Django 4.2.7 on 2026-04-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_metalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="metalprice",
            name="price_22k",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="22K gold price (auto-calculated)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
