# Generated by Django 4.2.7 on 2026-06-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_metalprice_price_22k"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metal_type",
                    models.CharField(
                        choices=[
                            ("GOLD_24K", "24K Gold"),
                            ("GOLD_22K", "22K Gold"),
                            ("GOLD_18K", "18K Gold"),
                            ("SILVER", "Silver"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "purity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "rate_per_gram",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "making_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "making_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed (₹/g)"),
                            ("PERCENTAGE", "Percentage (%)"),
                        ],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Metal Rates",
                "ordering": ["metal_type"],
            },
        ),
        migrations.CreateModel(
            name="PopupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("status", models.BooleanField(default=True)),
                ("show_on_refresh", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Popup Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "metal_type",
                    models.CharField(
                        choices=[
                            ("GOLD_24K", "24K Gold"),
                            ("GOLD_22K", "22K Gold"),
                            ("GOLD_18K", "18K Gold"),
                            ("SILVER", "Silver"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="jewelry_products/"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "making_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed (₹/g)"),
                            ("PERCENTAGE", "Percentage (%)"),
                            ("USE_RATE", "Use from Metal Rate"),
                        ],
                        default="USE_RATE",
                        max_length=20,
                    ),
                ),
                (
                    "making_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_products",
                        to="shop.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_products",
                        to="shop.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
