# Generated by Django 4.2.7 on 2026-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_metalrate_popupmessage_jewelryproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelryproduct",
            name="metal_type",
            field=models.CharField(
                help_text="Metal type (must match exactly with Metal Rate)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="metal_type",
            field=models.CharField(
                help_text="Metal type like '24K Gold', 'Silver'",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="purity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Purity percentage like 99.5, 91.6",
                max_digits=5,
            ),
        ),
    ]
