# Generated by Django 4.2.7 on 2026-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_jewelryproduct_metal_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metalrate',
            options={'ordering': ['order', 'metal_type'], 'verbose_name_plural': 'Metal Rates'},
        ),
        migrations.AddField(
            model_name='metalrate',
            name='order',
            field=models.IntegerField(default=0, help_text='Custom ordering (lower number comes first)'),
        ),
    ]
