# Generated by Django 5.2.15 on 2026-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_metalrate_options_metalrate_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the collection (e.g. Gold Ornaments)",
                        max_length=150,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Shop Collection",
                        help_text="Action text/Subtitle (e.g. Shop Collection)",
                        max_length=150,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image of the collection",
                        upload_to="signature_collections/",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        default="/shop/",
                        help_text="Link to collection (e.g. /shop/ or Django url path)",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower is first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this card from the slider",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Signature Collections",
                "ordering": ["order", "title"],
            },
        ),
    ]
