# Generated by Django 5.2.15 on 2026-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_signaturecollection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rating", models.PositiveIntegerField(default=5)),
                ("message", models.TextField()),
                (
                    "designation",
                    models.CharField(
                        blank=True, default="Verified Buyer", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="SignatureCollection",
        ),
        migrations.AlterModelOptions(
            name="metalrate",
            options={"ordering": ["metal_type"], "verbose_name_plural": "Metal Rates"},
        ),
        migrations.RemoveField(
            model_name="metalrate",
            name="order",
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="metal_type",
            field=models.CharField(
                choices=[
                    ("GOLD_24K", "24K Gold"),
                    ("GOLD_22K", "22K Gold"),
                    ("GOLD_18K", "18K Gold"),
                    ("SILVER", "Silver"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="metal_type",
            field=models.CharField(
                choices=[
                    ("GOLD_24K", "24K Gold"),
                    ("GOLD_22K", "22K Gold"),
                    ("GOLD_18K", "18K Gold"),
                    ("SILVER", "Silver"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="purity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
