# Generated by Django 5.2.15 on 2026-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_testimonial_delete_signaturecollection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("video", models.FileField(upload_to="reels/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="reels/covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Subcategories",
            },
        ),
        migrations.AddField(
            model_name="subcategory",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Show in 'Recommended for you' section"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Order of display (lower numbers first)"
            ),
        ),
    ]
