# Generated by Django 5.2.15 on 2026-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_reel_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="popupmessage",
            name="poster_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload discount poster image",
                null=True,
                upload_to="popup_posters/",
            ),
        ),
        migrations.AlterField(
            model_name="popupmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
