# Generated by Django 5.2.15 on 2026-06-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_popupmessage_poster_image_alter_popupmessage_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.jewellery"
            ),
        ),
    ]
