# Generated by Django 5.2.15 on 2026-07-18 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_wishlist_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Section title for Signature Collection",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, help_text="Section subtitle/description", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this section on homepage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Signature Collections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignatureCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Item title", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description for this item",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for this signature collection item",
                        null=True,
                        upload_to="signature_collection/",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order of display (lower numbers first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.signaturecollection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-id"],
            },
        ),
        migrations.RemoveField(
            model_name="jewellery",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="jewelleryimage",
            name="jewellery",
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.product",
            ),
        ),
        migrations.RemoveField(
            model_name="jewelryproduct",
            name="category",
        ),
        migrations.RemoveField(
            model_name="jewelryproduct",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="MetalPrice",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Products"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_available",
            new_name="in_stock",
        ),
        migrations.AddField(
            model_name="metalrate",
            name="show_gst",
            field=models.BooleanField(
                default=True, help_text="Show GST calculation on frontend"
            ),
        ),
        migrations.AddField(
            model_name="metalrate",
            name="show_making_charge",
            field=models.BooleanField(
                default=True, help_text="Show making charge value on frontend"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="calc_button_text",
            field=models.CharField(
                default="Calc", help_text="Text for Calculator button", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="calc_button_url",
            field=models.CharField(
                default="#live-calculator",
                help_text="URL path/anchor for Calculator button",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="rates_button_text",
            field=models.CharField(
                default="Rates", help_text="Text for Rates button", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="rates_button_url",
            field=models.CharField(
                default="/live-rates/",
                help_text="URL path for Rates button",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="shop_button_text",
            field=models.CharField(
                default="Shop", help_text="Text for Shop button", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="shop_button_url",
            field=models.CharField(
                default="/shop/", help_text="URL path for Shop button", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_calc_button",
            field=models.BooleanField(
                default=True, help_text="Toggle Calculator button visibility"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_message",
            field=models.BooleanField(
                default=True, help_text="Toggle message text visibility"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_poster_image",
            field=models.BooleanField(
                default=True, help_text="Toggle poster image visibility"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_rates_button",
            field=models.BooleanField(
                default=True, help_text="Toggle Rates button visibility"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_rates_grid",
            field=models.BooleanField(
                default=True, help_text="Toggle daily rates grid inside popup"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_shop_button",
            field=models.BooleanField(
                default=True, help_text="Toggle Shop button visibility"
            ),
        ),
        migrations.AddField(
            model_name="popupmessage",
            name="show_title",
            field=models.BooleanField(
                default=True, help_text="Toggle title visibility"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("ROSE_GOLD", "Rose Gold"),
                    ("PLATINUM", "Platinum"),
                    ("MULTI", "Multi-color"),
                ],
                default="GOLD",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="gold_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gst",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_manual_price",
            field=models.BooleanField(
                default=False,
                help_text="Check this to manually enter pricing values (Metal Value, Making Charges, GST) and prevent automatic updates based on daily rates.",
                verbose_name="Manual Price Override",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="making_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="occasion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="platinum_purity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("950", "950 Platinum"),
                    ("900", "900 Platinum"),
                    ("OTHER", "Other"),
                ],
                default="950",
                help_text="Platinum purity (only relevant when metal_type is Platinum)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="platinum_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="platinum_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="silver_purity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STERLING", "Sterling (925)"),
                    ("999", "999 Fine Silver"),
                    ("OTHER", "Other"),
                ],
                default="STERLING",
                help_text="Silver purity (only relevant when metal_type is Silver)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="silver_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="silver_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIAMOND", "Diamond"),
                    ("RUBY", "Ruby"),
                    ("EMERALD", "Emerald"),
                    ("SAPPHIRE", "Sapphire"),
                    ("PEARL", "Pearl"),
                    ("AMETHYST", "Amethyst"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stone_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOLD_24K", "24K Gold"),
                    ("GOLD_22K", "22K Gold"),
                    ("GOLD_18K", "18K Gold"),
                    ("SILVER", "92.5 Silver Jewellery"),
                ],
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="purity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="rate_per_gram",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Show this metal rate block on frontend"
            ),
        ),
        migrations.AlterField(
            model_name="popupmessage",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="badge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "New Arrival"),
                    ("SALE", "On Sale"),
                    ("BEST", "Best Seller"),
                    ("TRENDING", "Trending"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="diamond_clarity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="diamond_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="diamond_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gold_purity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18K", "18K"),
                    ("22K", "22K"),
                    ("24K", "24K"),
                    ("OTHER", "Other"),
                ],
                default="22K",
                help_text="Gold purity (only relevant when metal_type is Gold)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gold_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="jewellery/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("PLATINUM", "Platinum"),
                ],
                default="GOLD",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jewellery_items",
                to="shop.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="jewellery/gallery/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.product",
            ),
        ),
        migrations.AlterField(
            model_name="reel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="reels/"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="JewelleryImage",
        ),
        migrations.DeleteModel(
            name="Jewellery",
        ),
        migrations.DeleteModel(
            name="JewelryProduct",
        ),
        migrations.AlterModelTable(
            name="product",
            table="shop_jewellery",
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="shop_jewelleryimage",
        ),
    ]
