# Generated by Django 5.2.15 on 2026-07-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_signaturecollection_signaturecollectionitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metalrate",
            name="metal_type",
            field=models.CharField(
                blank=True,
                help_text="Enter metal rate code (e.g. GOLD_24K, GOLD_22K, GOLD_18K, GOLD_14K, GOLD_9K, SILVER_999, SILVER_STERLING, SILVER, PLATINUM).",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gold_purity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("9K", "9K"),
                    ("10K", "10K"),
                    ("14K", "14K"),
                    ("18K", "18K"),
                    ("22K", "22K"),
                    ("24K", "24K"),
                    ("OTHER", "Other"),
                ],
                default="22K",
                help_text="Gold purity (only relevant when metal_type is Gold)",
                max_length=10,
                null=True,
            ),
        ),
    ]
