# Generated by Django 5.2.15 on 2026-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_metalrate_metal_type_alter_product_gold_purity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Order of display (lower numbers first)"
            ),
        ),
    ]
