# Generated by Django 5.2.15 on 2026-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_alter_category_options_category_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional product/customer image uploaded with feedback",
                null=True,
                upload_to="testimonials/",
            ),
        ),
    ]
