# Generated by Django 5.2.15 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_testimonial_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gross_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                help_text="Gross weight in grams",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="net_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                help_text="Net metal weight in grams",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="diamond_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gold_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="platinum_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="silver_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("MOISSANITE", "Moissanite"),
                    ("LAB_GROWN", "Lab Grown"),
                    ("AMERICAN", "American Diamond"),
                    ("DIAMOND", "Diamond"),
                    ("RUBY", "Ruby"),
                    ("EMERALD", "Emerald"),
                    ("SAPPHIRE", "Sapphire"),
                    ("PEARL", "Pearl"),
                    ("AMETHYST", "Amethyst"),
                    ("OTHER", "Other"),
                ],
                default="NONE",
                max_length=20,
                null=True,
            ),
        ),
    ]
