# Generated by Django 5.2.15 on 2026-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_product_gross_weight_product_net_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="making_per_gram",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Making charges per gram in ₹. Enter manually for Gold, Silver, and Platinum products.",
                max_digits=10,
                null=True,
                verbose_name="Making Charge Per Gram (₹/g)",
            ),
        ),
    ]
