# Generated by Django 5.2.15 on 2026-08-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_product_making_per_gram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="silver_purity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STERLING", "Sterling (925)"),
                    ("999", "999 Fine Silver"),
                    ("70", "Silver (70%)"),
                    ("50", "Silver (50%)"),
                    ("OTHER", "Other"),
                ],
                default="STERLING",
                help_text="Silver purity (only relevant when metal_type is Silver)",
                max_length=20,
                null=True,
            ),
        ),
    ]
